# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'
#-source 'https://github.com/CocoaPods/Specs.git'
target 'ZJSDKDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
#  post_install do |installer|
#    installer.pods_project.targets.each do |target|
#      target.build_configurations.each do |config|
#        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
#      end
#    end
#  end

pod 'ZJSDK', :path =>"../"
pod 'ZJSDK/ZJSDKModuleMeiShu', :path => '../'
pod 'ZJSDK/ZJSDKModuleFS', :path => '../'

  
end
 
