# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'
#-source 'https://github.com/CocoaPods/Specs.git'

#source 'https://gitee.com/jyadteam/JYSpecs.git'


target 'ZJSDKDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
#  post_install do |installer|
#    installer.pods_project.targets.each do |target|
#      target.build_configurations.each do |config|
#        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
#      end
#    end
#  end

pod 'ZJSDK', :path =>"../"
pod 'ZJSDK/ZJSDKModuleMeiShu', :path => '../'
pod 'ZJSDK/ZJSDKModuleFS', :path => '../'
pod 'ZJSDK/ZJSDKModuleJuTui', :path => '../'


#pod 'ZJSDK/ZJSDKModuleGDT', :path => '../'

#pod 'Ads-CN/BUAdSDK', '7.5.0.8'

#pod 'GDTMobSDK', '4.15.90'

#pod 'SigmobAd-iOS', '4.20.12'

#pod 'JYAdSDK', '2.1.0'

#pod 'ZJSDK', '2.6.1.8'

#pod 'AnyThinkiOS', '6.5.71'
#pod 'AnyThinkBanner'
#pod 'AnyThinkinterstitial'
#pod 'AnyThinkMediaVideo'
#pod 'AnyThinkNative'
#pod 'AnyThinkRewardedVideo'
#pod 'AnyThinkSplash'

#pod 'ZJSDK/ZJSDKModuleTaKu', :path => '../'

#pod 'AnyThinkiOS','6.5.47'
##Anythink Kuying Adx SDK(necessary)
#pod 'AnyThinkMediationAdxSmartdigimktCNAdapter','6.5.66.0'

#pod 'SmartdigimktCNSDK','6.5.66'

#pod 'ZJSDK/ZJSDKModuleSIG', '2.6.2.2'

end
 
